package com.wdg.dao;

import com.wdg.entity.ExamResult;
import java.util.List;

public interface ExamResultMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_result
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_result
     *
     * @mbg.generated
     */
    int insert(ExamResult record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_result
     *
     * @mbg.generated
     */
    ExamResult selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_result
     *
     * @mbg.generated
     */
    List<ExamResult> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_result
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ExamResult record);
}