package com.wdg.dao;

import com.wdg.entity.KnowledgeComment;
import java.util.List;

public interface KnowledgeCommentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table knowledge_comment
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table knowledge_comment
     *
     * @mbg.generated
     */
    int insert(KnowledgeComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table knowledge_comment
     *
     * @mbg.generated
     */
    KnowledgeComment selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table knowledge_comment
     *
     * @mbg.generated
     */
    List<KnowledgeComment> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table knowledge_comment
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(KnowledgeComment record);
}