package com.wdg.dao;

import com.wdg.entity.QuestionSubject;
import java.util.List;

public interface QuestionSubjectMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question_subject
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question_subject
     *
     * @mbg.generated
     */
    int insert(QuestionSubject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question_subject
     *
     * @mbg.generated
     */
    QuestionSubject selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question_subject
     *
     * @mbg.generated
     */
    List<QuestionSubject> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question_subject
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(QuestionSubject record);
}